spring.application.name=roads

spring.datasource.url=jdbc:postgresql://localhost:5432/roads
spring.datasource.username=postgres
spring.datasource.password=1996
spring.datasource.driver-class-name=org.postgresql.Driver

# application.properties
server.port=8081

