spring.application.name=roads

spring.datasource.url=jdbc:postgresql://localhost:5432/roads
spring.datasource.username=postgres
spring.datasource.password=1996
spring.datasource.driver-class-name=org.postgresql.Driver

# application.properties
server.port=8080

#sta propriedade, quando corrigida, configura o JPA para exibir as instruções SQL geradas no console, o que é útil para depuração.
spring.jpa.show-sql=true
#configura o DBCP2 para testar conexões enquanto estão ociosas, garantindo que conexões inativas sejam válidas.
spring.datasource.dbcp2.test-while-idle=true
#configura o DBCP2 para testar conexões antes de serem emprestadas, garantindo que conexões inativas sejam válidas.
spring.datasource.dbcp2.validation-query=SELECT 1

# Define a estratégia de nomenclatura implícita do Hibernate. ImplicitNamingStrategyComponentPathImpl é uma implementação que aplica convenções de nomenclatura específicas do Hibernate, como a conversão de nomes de camel case para snake case.
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
#Define a estratégia de nomenclatura física do Hibernate. SpringPhysicalNamingStrategy é uma implementação que aplica convenções de nomenclatura específicas do Spring Boot, como a conversão de nomes de camel case para snake case.
spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy




