spring.application.name=roads

spring.datasource.url=jdbc:postgresql://localhost:5432/roads
spring.datasource.username=postgres
spring.datasource.password=1996
spring.datasource.driver-class-name=org.postgresql.Driver


# application.properties
server.port=8080

# Configurações de Conexão
spring.datasource.dbcp2.test-while-idle=true
spring.datasource.dbcp2.validation-query=SELECT 1

# Configurações do JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configurações de Nomenclatura
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Configuração Adicional
spring.jpa.properties.hibernate.dialect.legacy_limit_handler=true